apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voxera-knowledge-pvc
  labels:
    {{- include "voxera.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  {{- if .Values.api.storageClassName }}
  storageClassName: {{ .Values.api.storageClassName }}
  {{- end }}
