"""Streaming STT engine interface and mock implementation."""

import asyncio
import random
import uuid
from abc import ABC, abstractmethod
from typing import Callable, Optional

from app.core.logger import get_logger
from app.stt.models import TranscriptEvent, TranscriptType

logger = get_logger(__name__)


class StreamingSTTEngine(ABC):
    """Abstract interface for streaming STT engines."""

    @abstractmethod
    async def process_audio(self, frame: bytes) -> Optional[TranscriptEvent]:
        """Process audio frame and return partial transcript if available.

        Args:
            frame: Audio frame bytes (20ms PCM16)

        Returns:
            TranscriptEvent if partial transcript available, None otherwise
        """
        pass

    @abstractmethod
    async def finalize_utterance(self) -> Optional[TranscriptEvent]:
        """Finalize current utterance and return final transcript.

        Returns:
            TranscriptEvent with final transcript or None if no utterance
        """
        pass

    @abstractmethod
    async def reset(self) -> None:
        """Reset engine state (e.g., on new utterance or interruption)."""
        pass


class MockSTTEngine(StreamingSTTEngine):
    """Mock STT engine for testing and development.

    Simulates partial transcripts every N frames and final transcripts
    on silence or explicit finalization.
    """

    def __init__(
        self,
        partial_interval: int = 3,  # More frequent partials for better verification
        word_probability: float = 0.25,  # Higher probability to generate words faster
        silence_threshold: int = 15,  # Longer silence before finalizing
    ):
        """Initialize mock STT engine.

        Args:
            partial_interval: Emit partial transcript every N frames (default: 3)
            word_probability: Probability of generating a word per frame (default: 0.25)
            silence_threshold: Frames of silence before finalizing (default: 15)
        """
        self.partial_interval = partial_interval
        self.word_probability = word_probability
        self.silence_threshold = silence_threshold

        self._utterance_id: Optional[str] = None
        self._frame_count = 0
        self._silence_count = 0
        self._words: list[str] = []
        self._mock_words = [
            "hello",
            "yes",
            "no",
            "please",
            "thank",
            "you",
            "help",
            "support",
            "account",
            "balance",
            "information",
            "service",
        ]

    async def process_audio(self, frame: bytes) -> Optional[TranscriptEvent]:
        """Process audio frame and occasionally return partial transcript.

        Args:
            frame: Audio frame bytes (can be dummy bytes for mock engine)

        Returns:
            TranscriptEvent with partial transcript if interval reached, None otherwise
        """
        # Initialize utterance ID on first frame
        if self._utterance_id is None:
            self._utterance_id = str(uuid.uuid4())
            logger.debug(
                "New utterance started in STT engine",
                extra_fields={"utterance_id": self._utterance_id},
            )

        self._frame_count += 1

        # Simulate word generation (works even with dummy bytes)
        if random.random() < self.word_probability:
            word = random.choice(self._mock_words)
            self._words.append(word)
            self._silence_count = 0  # Reset silence counter
            logger.debug(
                "Word generated by mock STT engine",
                extra_fields={
                    "word": word,
                    "frame_count": self._frame_count,
                    "total_words": len(self._words),
                },
            )
        else:
            self._silence_count += 1

        # Emit partial transcript at intervals
        if self._frame_count % self.partial_interval == 0 and self._words:
            transcript = " ".join(self._words)
            confidence = random.uniform(0.7, 0.95)

            event = TranscriptEvent(
                type=TranscriptType.PARTIAL,
                utterance_id=self._utterance_id,
                transcript=transcript,
                confidence=confidence,
            )

            logger.info(
                "Partial transcript produced by STT engine",
                extra_fields={
                    "utterance_id": self._utterance_id,
                    "transcript": transcript,
                    "confidence": round(confidence, 3),
                    "frame_count": self._frame_count,
                    "word_count": len(self._words),
                },
            )

            return event

        # Auto-finalize on silence
        if self._silence_count >= self.silence_threshold and self._words:
            logger.debug(
                "Silence threshold reached, finalizing utterance",
                extra_fields={
                    "utterance_id": self._utterance_id,
                    "silence_count": self._silence_count,
                    "threshold": self.silence_threshold,
                },
            )
            return await self.finalize_utterance()

        return None

    async def finalize_utterance(self) -> Optional[TranscriptEvent]:
        """Finalize current utterance and return final transcript.

        Returns:
            TranscriptEvent with final transcript or None if no words
        """
        if not self._words:
            logger.debug("Finalize called but no words to finalize")
            return None

        transcript = " ".join(self._words)
        confidence = random.uniform(0.85, 0.99)
        utterance_id = self._utterance_id or str(uuid.uuid4())

        event = TranscriptEvent(
            type=TranscriptType.FINAL,
            utterance_id=utterance_id,
            transcript=transcript,
            confidence=confidence,
        )

        logger.info(
            "Final transcript produced by STT engine",
            extra_fields={
                "utterance_id": utterance_id,
                "transcript": transcript,
                "confidence": round(confidence, 3),
                "word_count": len(self._words),
                "frame_count": self._frame_count,
            },
        )

        # Reset for next utterance
        await self.reset()

        return event

    async def reset(self) -> None:
        """Reset engine state for new utterance."""
        self._utterance_id = None
        self._frame_count = 0
        self._silence_count = 0
        self._words.clear()
